name: RSpec

on:
  push:
  pull_request:

jobs:
  rspec:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build Docker image
        working-directory: ./http_requester
        run: docker build -t http_requester_test .

      - name: Run RSpec in Docker
        working-directory: ./http_requester
        run: docker run --rm http_requester_test bundle exec rspec