// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using UptimeDaddy.API.Data;

#nullable disable

namespace UptimeDaddy.API.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260709193000_AddEmailNotificationPreferences")]
    partial class AddEmailNotificationPreferences
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("UptimeDaddy.API.Models.DashboardBoard", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<bool>("IsPublished")
                        .HasColumnType("boolean")
                        .HasColumnName("is_published");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<string>("ShareToken")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("share_token");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasDatabaseName("ix_dashboard_boards_name_published_unique")
                        .HasFilter("is_published = TRUE");

                    b.HasIndex("ShareToken")
                        .IsUnique()
                        .HasDatabaseName("ix_dashboard_boards_share_token");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_dashboard_boards_user_id");

                    b.HasIndex("UserId", "Name")
                        .IsUnique()
                        .HasDatabaseName("ix_dashboard_boards_user_id_name_unique");

                    b.ToTable("dashboard_boards");
                });

            modelBuilder.Entity("UptimeDaddy.API.Models.DashboardBoardItem", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long>("DashboardBoardId")
                        .HasColumnType("bigint")
                        .HasColumnName("dashboard_board_id");

                    b.Property<string>("DisplayLabel")
                        .HasColumnType("text")
                        .HasColumnName("display_label");

                    b.Property<long>("MonitorId")
                        .HasColumnType("bigint")
                        .HasColumnName("monitor_id");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer")
                        .HasColumnName("sort_order");

                    b.HasKey("Id");

                    b.HasIndex("MonitorId");

                    b.HasIndex("DashboardBoardId", "SortOrder")
                        .HasDatabaseName("ix_dashboard_board_items_board_sort");

                    b.ToTable("dashboard_board_items");
                });

            modelBuilder.Entity("UptimeDaddy.API.Models.DiscordIntegration", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("DefaultChannelId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("default_channel_id");

                    b.Property<bool>("Enabled")
                        .HasColumnType("boolean")
                        .HasColumnName("enabled");

                    b.Property<string>("GuildId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("guild_id");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .IsUnique()
                        .HasDatabaseName("ix_discord_integrations_user_id_unique");

                    b.ToTable("discord_integrations");
                });

            modelBuilder.Entity("UptimeDaddy.API.Models.EmailNotificationPreference", b =>
                {
                    b.Property<long>("UserId")
                        .HasColumnType("bigint")
                        .HasColumnName("user_id");

                    b.Property<bool>("Enabled")
                        .HasColumnType("boolean")
                        .HasColumnName("enabled");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("UserId");

                    b.ToTable("email_notification_preferences");
                });

            modelBuilder.Entity("UptimeDaddy.API.Models.DiscordMonitorSubscription", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("ChannelIdOverride")
                        .HasColumnType("text")
                        .HasColumnName("channel_id_override");

                    b.Property<long>("MonitorPathId")
                        .HasColumnType("bigint")
                        .HasColumnName("monitor_path_id");

                    b.Property<bool>("NotificationEnabled")
                        .HasColumnType("boolean")
                        .HasColumnName("notification_enabled");

                    b.HasKey("Id");

                    b.HasIndex("MonitorPathId")
                        .IsUnique()
                        .HasDatabaseName("ix_discord_monitor_subscriptions_monitor_path_id_unique");

                    b.ToTable("discord_monitor_subscriptions");
                });

            modelBuilder.Entity("UptimeDaddy.API.Models.DiscordReportSchedule", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("ChannelId")
                        .HasColumnType("text")
                        .HasColumnName("channel_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("CronExpression")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("cron_expression");

                    b.Property<bool>("Enabled")
                        .HasColumnType("boolean")
                        .HasColumnName("enabled");

                    b.Property<DateTime?>("LastRunAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_run_at");

                    b.Property<string>("ReportType")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("report_type");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_discord_report_schedules_user_id");

                    b.ToTable("discord_report_schedules");
                });

            modelBuilder.Entity("UptimeDaddy.API.Models.Measurement", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<double>("ConnectMs")
                        .HasColumnType("double precision")
                        .HasColumnName("connect_ms");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<double>("DnsLookupMs")
                        .HasColumnType("double precision")
                        .HasColumnName("dns_lookup_ms");

                    b.Property<bool?>("KeywordMatched")
                        .HasColumnType("boolean")
                        .HasColumnName("keyword_matched");

                    b.Property<long>("MonitorPathId")
                        .HasColumnType("bigint")
                        .HasColumnName("monitor_path_id");

                    b.Property<int>("StatusCode")
                        .HasColumnType("integer")
                        .HasColumnName("status_code");

                    b.Property<double>("TimeToFirstByteMs")
                        .HasColumnType("double precision")
                        .HasColumnName("time_to_first_byte_ms");

                    b.Property<double>("TlsHandshakeMs")
                        .HasColumnType("double precision")
                        .HasColumnName("tls_handshake_ms");

                    b.Property<double>("TotalTimeMs")
                        .HasColumnType("double precision")
                        .HasColumnName("total_time_ms");

                    b.HasKey("Id");

                    b.HasIndex("MonitorPathId", "CreatedAt")
                        .IsDescending(false, true)
                        .HasDatabaseName("ix_measurements_monitor_path_id_created_at_desc");

                    b.ToTable("measurements");
                });

            modelBuilder.Entity("UptimeDaddy.API.Models.MonitorIncidentEvent", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<double?>("DowntimeDurationMs")
                        .HasColumnType("double precision")
                        .HasColumnName("downtime_duration_ms");

                    b.Property<bool>("IsUp")
                        .HasColumnType("boolean")
                        .HasColumnName("is_up");

                    b.Property<long>("MonitorPathId")
                        .HasColumnType("bigint")
                        .HasColumnName("monitor_path_id");

                    b.Property<DateTime>("OccurredAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("occurred_at");

                    b.Property<int>("StatusCode")
                        .HasColumnType("integer")
                        .HasColumnName("status_code");

                    b.Property<double>("TotalTimeMs")
                        .HasColumnType("double precision")
                        .HasColumnName("total_time_ms");

                    b.HasKey("Id");

                    b.HasIndex("MonitorPathId", "OccurredAt")
                        .IsDescending(false, true)
                        .HasDatabaseName("ix_monitor_incident_events_path_occurred_desc");

                    b.ToTable("monitor_incident_events");
                });

            modelBuilder.Entity("UptimeDaddy.API.Models.MonitorIncidentState", b =>
                {
                    b.Property<long>("MonitorPathId")
                        .HasColumnType("bigint")
                        .HasColumnName("monitor_path_id");

                    b.Property<bool>("Initialized")
                        .HasColumnType("boolean")
                        .HasColumnName("initialized");

                    b.Property<bool>("LastIsUp")
                        .HasColumnType("boolean")
                        .HasColumnName("last_is_up");

                    b.Property<DateTime?>("LastNotificationSentAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_notification_sent_at");

                    b.Property<int>("LastStatusCode")
                        .HasColumnType("integer")
                        .HasColumnName("last_status_code");

                    b.Property<DateTime>("LastTransitionAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_transition_at");

                    b.HasKey("MonitorPathId");

                    b.ToTable("monitor_incident_states");
                });

            modelBuilder.Entity("UptimeDaddy.API.Models.MonitorPath", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("DisplayLabel")
                        .HasColumnType("text")
                        .HasColumnName("display_label");

                    b.Property<string>("Keyword")
                        .HasColumnType("text")
                        .HasColumnName("keyword");

                    b.Property<bool>("KeywordMustContain")
                        .HasColumnType("boolean")
                        .HasColumnName("keyword_must_contain");

                    b.Property<long>("MonitorId")
                        .HasColumnType("bigint")
                        .HasColumnName("monitor_id");

                    b.Property<string>("Path")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("path");

                    b.HasKey("Id");

                    b.HasIndex("MonitorId", "Path")
                        .IsUnique()
                        .HasDatabaseName("ix_monitor_paths_monitor_id_path_unique");

                    b.ToTable("monitor_paths");
                });

            modelBuilder.Entity("UptimeDaddy.API.Models.SiteMonitor", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("BaseUrl")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("base_url");

                    b.Property<string>("FaviconBase64")
                        .HasColumnType("text")
                        .HasColumnName("faviconbase64");

                    b.Property<int>("IntervalTime")
                        .HasColumnType("integer")
                        .HasColumnName("interval_time");

                    b.Property<DateTime?>("SslExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("ssl_expires_at");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_monitors_user_id");

                    b.HasIndex("UserId", "BaseUrl")
                        .IsUnique()
                        .HasDatabaseName("ix_monitors_user_id_base_url_unique");

                    b.ToTable("monitors");
                });

            modelBuilder.Entity("UptimeDaddy.API.Models.User", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("email");

                    b.Property<string>("Fullname")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("fullName");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("password_hash");

                    b.HasKey("Id");

                    b.ToTable("accounts");
                });

            modelBuilder.Entity("UptimeDaddy.API.Models.DashboardBoard", b =>
                {
                    b.HasOne("UptimeDaddy.API.Models.User", "User")
                        .WithMany("DashboardBoards")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("UptimeDaddy.API.Models.DashboardBoardItem", b =>
                {
                    b.HasOne("UptimeDaddy.API.Models.DashboardBoard", "DashboardBoard")
                        .WithMany("Items")
                        .HasForeignKey("DashboardBoardId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("UptimeDaddy.API.Models.SiteMonitor", "Monitor")
                        .WithMany("DashboardBoardItems")
                        .HasForeignKey("MonitorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DashboardBoard");

                    b.Navigation("Monitor");
                });

            modelBuilder.Entity("UptimeDaddy.API.Models.DiscordIntegration", b =>
                {
                    b.HasOne("UptimeDaddy.API.Models.User", "User")
                        .WithOne("DiscordIntegration")
                        .HasForeignKey("UptimeDaddy.API.Models.DiscordIntegration", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("UptimeDaddy.API.Models.EmailNotificationPreference", b =>
                {
                    b.HasOne("UptimeDaddy.API.Models.User", "User")
                        .WithOne("EmailNotificationPreference")
                        .HasForeignKey("UptimeDaddy.API.Models.EmailNotificationPreference", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("UptimeDaddy.API.Models.DiscordMonitorSubscription", b =>
                {
                    b.HasOne("UptimeDaddy.API.Models.MonitorPath", "MonitorPath")
                        .WithOne("DiscordMonitorSubscription")
                        .HasForeignKey("UptimeDaddy.API.Models.DiscordMonitorSubscription", "MonitorPathId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MonitorPath");
                });

            modelBuilder.Entity("UptimeDaddy.API.Models.DiscordReportSchedule", b =>
                {
                    b.HasOne("UptimeDaddy.API.Models.User", "User")
                        .WithMany("DiscordReportSchedules")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("UptimeDaddy.API.Models.Measurement", b =>
                {
                    b.HasOne("UptimeDaddy.API.Models.MonitorPath", "MonitorPath")
                        .WithMany("Measurements")
                        .HasForeignKey("MonitorPathId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MonitorPath");
                });

            modelBuilder.Entity("UptimeDaddy.API.Models.MonitorIncidentEvent", b =>
                {
                    b.HasOne("UptimeDaddy.API.Models.MonitorPath", "MonitorPath")
                        .WithMany()
                        .HasForeignKey("MonitorPathId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MonitorPath");
                });

            modelBuilder.Entity("UptimeDaddy.API.Models.MonitorIncidentState", b =>
                {
                    b.HasOne("UptimeDaddy.API.Models.MonitorPath", "MonitorPath")
                        .WithOne("MonitorIncidentState")
                        .HasForeignKey("UptimeDaddy.API.Models.MonitorIncidentState", "MonitorPathId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MonitorPath");
                });

            modelBuilder.Entity("UptimeDaddy.API.Models.MonitorPath", b =>
                {
                    b.HasOne("UptimeDaddy.API.Models.SiteMonitor", "Monitor")
                        .WithMany("Paths")
                        .HasForeignKey("MonitorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Monitor");
                });

            modelBuilder.Entity("UptimeDaddy.API.Models.SiteMonitor", b =>
                {
                    b.HasOne("UptimeDaddy.API.Models.User", "User")
                        .WithMany("Monitors")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("UptimeDaddy.API.Models.DashboardBoard", b =>
                {
                    b.Navigation("Items");
                });

            modelBuilder.Entity("UptimeDaddy.API.Models.MonitorPath", b =>
                {
                    b.Navigation("DiscordMonitorSubscription");

                    b.Navigation("Measurements");

                    b.Navigation("MonitorIncidentState");
                });

            modelBuilder.Entity("UptimeDaddy.API.Models.SiteMonitor", b =>
                {
                    b.Navigation("DashboardBoardItems");

                    b.Navigation("Paths");
                });

            modelBuilder.Entity("UptimeDaddy.API.Models.User", b =>
                {
                    b.Navigation("DashboardBoards");

                    b.Navigation("DiscordIntegration");

                    b.Navigation("EmailNotificationPreference");

                    b.Navigation("DiscordReportSchedules");

                    b.Navigation("Monitors");
                });
#pragma warning restore 612, 618
        }
    }
}
