// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using UptimeDaddy.API.Data;

#nullable disable

namespace UptimeDaddy.API.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260418095521_PublishedBoardNameGloballyUnique")]
    partial class PublishedBoardNameGloballyUnique
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("UptimeDaddy.API.Models.DashboardBoard", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<bool>("IsPublished")
                        .HasColumnType("boolean")
                        .HasColumnName("is_published");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<string>("ShareToken")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("share_token");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasDatabaseName("ix_dashboard_boards_name_published_unique")
                        .HasFilter("is_published = TRUE");

                    b.HasIndex("ShareToken")
                        .IsUnique()
                        .HasDatabaseName("ix_dashboard_boards_share_token");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_dashboard_boards_user_id");

                    b.HasIndex("UserId", "Name")
                        .IsUnique()
                        .HasDatabaseName("ix_dashboard_boards_user_id_name_unique");

                    b.ToTable("dashboard_boards");
                });

            modelBuilder.Entity("UptimeDaddy.API.Models.DashboardBoardItem", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long>("DashboardBoardId")
                        .HasColumnType("bigint")
                        .HasColumnName("dashboard_board_id");

                    b.Property<string>("DisplayLabel")
                        .HasColumnType("text")
                        .HasColumnName("display_label");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer")
                        .HasColumnName("sort_order");

                    b.Property<long>("WebsiteId")
                        .HasColumnType("bigint")
                        .HasColumnName("website_id");

                    b.HasKey("Id");

                    b.HasIndex("WebsiteId");

                    b.HasIndex("DashboardBoardId", "SortOrder")
                        .HasDatabaseName("ix_dashboard_board_items_board_sort");

                    b.ToTable("dashboard_board_items");
                });

            modelBuilder.Entity("UptimeDaddy.API.Models.Measurement", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<double>("ConnectMs")
                        .HasColumnType("double precision")
                        .HasColumnName("connect_ms");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<double>("DnsLookupMs")
                        .HasColumnType("double precision")
                        .HasColumnName("dns_lookup_ms");

                    b.Property<int>("StatusCode")
                        .HasColumnType("integer")
                        .HasColumnName("status_code");

                    b.Property<double>("TimeToFirstByteMs")
                        .HasColumnType("double precision")
                        .HasColumnName("time_to_first_byte_ms");

                    b.Property<double>("TlsHandshakeMs")
                        .HasColumnType("double precision")
                        .HasColumnName("tls_handshake_ms");

                    b.Property<double>("TotalTimeMs")
                        .HasColumnType("double precision")
                        .HasColumnName("total_time_ms");

                    b.Property<long>("WebsiteId")
                        .HasColumnType("bigint")
                        .HasColumnName("website_id");

                    b.HasKey("Id");

                    b.HasIndex("WebsiteId", "CreatedAt")
                        .IsDescending(false, true)
                        .HasDatabaseName("ix_measurements_website_id_created_at_desc");

                    b.ToTable("measurements");
                });

            modelBuilder.Entity("UptimeDaddy.API.Models.User", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("email");

                    b.Property<string>("Fullname")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("fullName");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("password_hash");

                    b.HasKey("Id");

                    b.ToTable("accounts");
                });

            modelBuilder.Entity("UptimeDaddy.API.Models.Website", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("FaviconBase64")
                        .HasColumnType("text")
                        .HasColumnName("faviconbase64");

                    b.Property<int>("IntervalTime")
                        .HasColumnType("integer")
                        .HasColumnName("interval_time");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("url");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_websites_user_id");

                    b.ToTable("websites");
                });

            modelBuilder.Entity("UptimeDaddy.API.Models.DashboardBoard", b =>
                {
                    b.HasOne("UptimeDaddy.API.Models.User", "User")
                        .WithMany("DashboardBoards")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("UptimeDaddy.API.Models.DashboardBoardItem", b =>
                {
                    b.HasOne("UptimeDaddy.API.Models.DashboardBoard", "DashboardBoard")
                        .WithMany("Items")
                        .HasForeignKey("DashboardBoardId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("UptimeDaddy.API.Models.Website", "Website")
                        .WithMany("DashboardBoardItems")
                        .HasForeignKey("WebsiteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DashboardBoard");

                    b.Navigation("Website");
                });

            modelBuilder.Entity("UptimeDaddy.API.Models.Measurement", b =>
                {
                    b.HasOne("UptimeDaddy.API.Models.Website", "Website")
                        .WithMany("Measurements")
                        .HasForeignKey("WebsiteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Website");
                });

            modelBuilder.Entity("UptimeDaddy.API.Models.Website", b =>
                {
                    b.HasOne("UptimeDaddy.API.Models.User", "User")
                        .WithMany("Websites")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("UptimeDaddy.API.Models.DashboardBoard", b =>
                {
                    b.Navigation("Items");
                });

            modelBuilder.Entity("UptimeDaddy.API.Models.User", b =>
                {
                    b.Navigation("DashboardBoards");

                    b.Navigation("Websites");
                });

            modelBuilder.Entity("UptimeDaddy.API.Models.Website", b =>
                {
                    b.Navigation("DashboardBoardItems");

                    b.Navigation("Measurements");
                });
#pragma warning restore 612, 618
        }
    }
}
