# frozen_string_literal: true

source "https://rubygems.org"

gem "dotenv"
gem "faraday"
gem "faraday-follow_redirects"
gem "faraday-retry"
gem "mqtt"

group :test do
  gem "rspec", "~> 3.13"
  gem "webmock", "~> 3.24"
end
